name: Python checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install --dev
    - name: Lint
      run: pipenv run ./lint.sh
    - name: Test
      run: pipenv run ./test.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
